[package]
name = "mooloop-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
mooloop-core = { workspace = true }
mooloop-engine = { workspace = true }
slint = { workspace = true }

[build-dependencies]
slint-build = { workspace = true }
