[package]
name = "mooloop-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
mooloop-core = { workspace = true }
mooloop-dsp = { workspace = true }
mooloop-engine = { workspace = true }
mooloop-project = { workspace = true }
slint = { workspace = true }
symphonia = {
    version = "0.6.1",
    default-features = false,
    features = ["aiff", "flac", "mp3", "ogg", "opt-simd", "pcm", "vorbis", "wav"]
}
serde = { workspace = true }
toml = { workspace = true }

[build-dependencies]
slint-build = { workspace = true }

[dev-dependencies]
hound = "3"
tempfile = "3"
i-slint-backend-testing = { version = "1.17", features = ["renderer-software"] }
